config/routes.rb
Eval::Application.routes.draw do
  resources :years

  resources :categories

  resources :evaluations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :evalists

  devise_for :views

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :registerable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category, :category_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :registerable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :image, :name, :is_evaluator, :evaluator_id, :marca
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  has_attached_file :image, styles: { tiny:  "30x30#",
    :thumbnail => "60x60#"},
    :default_url => "/assets/default_tiny.png"
  # attr_accessible :title, :body
  def admin?
    self.is_admin == true
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/year.rb
class Year < ActiveRecord::Base
  attr_accessible :year, :year_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/controllers/evaluations_controller.rb
class EvaluationsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/years_controller.rb
class YearsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/evalists_helper.rb
module EvalistsHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :category %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.category %></td>
    <td><%= category.category_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @category.category %>
</p>

<p>
  <b>Category:</b>
  <%= @category.category_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/evaluations/edit.html.erb
<h1>Editing evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<h1>Listing evaluations</h1>

<table>
  <tr>
    <th>Category name 1</th>
    <th>Objective11</th>
    <th>Objective11 comments</th>
    <th>Objective11 eval comments</th>
    <th>Objective11 qualifier</th>
    <th>Objective11 evalq</th>
    <th>Nextpobjective11</th>
    <th>Objective21</th>
    <th>Objective21 comments</th>
    <th>Objective21 eval comments</th>
    <th>Objective21 qualifier</th>
    <th>Objective21 evalq</th>
    <th>Nextpobjective21</th>
    <th>Objective31</th>
    <th>Objective31 comments</th>
    <th>Objective31 eval comments</th>
    <th>Objective31 qualifier</th>
    <th>Objective31 evalq</th>
    <th>Nextpobjective31</th>
    <th>Category name 2</th>
    <th>Objective12</th>
    <th>Objective12 comments</th>
    <th>Objective12 eval comments</th>
    <th>Objective12 qualifier</th>
    <th>Objective12 evalq</th>
    <th>Nextpobjective12</th>
    <th>Objective22</th>
    <th>Objective22 comments</th>
    <th>Objective22 eval comments</th>
    <th>Objective22 qualifier</th>
    <th>Objective22 evalq</th>
    <th>Nextpobjective22</th>
    <th>Objective32</th>
    <th>Objective32 comments</th>
    <th>Objective32 eval comments</th>
    <th>Objective32 qualifier</th>
    <th>Objective32 evalq</th>
    <th>Nextpobjective32</th>
    <th>Category name 3</th>
    <th>Objective13</th>
    <th>Objective13 comments</th>
    <th>Objective13 eval comments</th>
    <th>Objective13 qualifier</th>
    <th>Objective13 evalq</th>
    <th>Nextpobjective13</th>
    <th>Objective23</th>
    <th>Objective23 comments</th>
    <th>Objective23 eval comments</th>
    <th>Objective23 qualifier</th>
    <th>Objective23 evalq</th>
    <th>Nextpobjective23</th>
    <th>Objective33</th>
    <th>Objective33 comments</th>
    <th>Objective33 eval comments</th>
    <th>Objective33 qualifier</th>
    <th>Objective33 evalq</th>
    <th>Category name 4</th>
    <th>Objective14</th>
    <th>Objective14 comments</th>
    <th>Objective14 eval comments</th>
    <th>Objective14 qualifier</th>
    <th>Objective14 evalq</th>
    <th>Nextpobjective14</th>
    <th>Objective24</th>
    <th>Objective24 comments</th>
    <th>Objective24 eval comments</th>
    <th>Objective24 qualifier</th>
    <th>Objective24 evalq</th>
    <th>Nextpobjective24</th>
    <th>Objective34</th>
    <th>Objective34 comments</th>
    <th>Objective34 eval comments</th>
    <th>Objective34 qualifier</th>
    <th>Objective34 evalq</th>
    <th>Nextpobjective34</th>
    <th>Nextpobjective34</th>
    <th>Category name 4</th>
    <th>Objective14</th>
    <th>Objective14 comments</th>
    <th>Objective14 eval comments</th>
    <th>Objective14 qualifier</th>
    <th>Objective14 evalq</th>
    <th>Nextpobjective14</th>
    <th>Objective24</th>
    <th>Objective24 comments</th>
    <th>Objective24 eval comments</th>
    <th>Objective24 qualifier</th>
    <th>Objective24 evalq</th>
    <th>Nextpobjective24</th>
    <th>Objective34</th>
    <th>Objective34 comments</th>
    <th>Objective34 eval comments</th>
    <th>Objective34 qualifier</th>
    <th>Objective34 evalq</th>
    <th>Nextpobjective34</th>
    <th>Category name 5</th>
    <th>Objective15</th>
    <th>Objective15 comments</th>
    <th>Objective15 eval comments</th>
    <th>Objective15 qualifier</th>
    <th>Objective15 evalq</th>
    <th>Nextpobjective15</th>
    <th>Objective25</th>
    <th>Objective25 comments</th>
    <th>Objective25 eval comments</th>
    <th>Objective25 qualifier</th>
    <th>Objective25 evalq</th>
    <th>Nextpobjective25</th>
    <th>Objective35</th>
    <th>Objective35 comments</th>
    <th>Objective35 eval comments</th>
    <th>Objective35 qualifier</th>
    <th>Objective35 evalq</th>
    <th>Nextpobjective35</th>
    <th>Overalleval</th>
    <th>User</th>
    <th>Year</th>
    <th>Evaluator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @evaluations.each do |evaluation| %>
  <tr>
    <td><%= evaluation.category_name_1 %></td>
    <td><%= evaluation.objective11 %></td>
    <td><%= evaluation.objective11_comments %></td>
    <td><%= evaluation.objective11_eval_comments %></td>
    <td><%= evaluation.objective11_qualifier %></td>
    <td><%= evaluation.objective11_evalq %></td>
    <td><%= evaluation.nextpobjective11 %></td>
    <td><%= evaluation.objective21 %></td>
    <td><%= evaluation.objective21_comments %></td>
    <td><%= evaluation.objective21_eval_comments %></td>
    <td><%= evaluation.objective21_qualifier %></td>
    <td><%= evaluation.objective21_evalq %></td>
    <td><%= evaluation.nextpobjective21 %></td>
    <td><%= evaluation.objective31 %></td>
    <td><%= evaluation.objective31_comments %></td>
    <td><%= evaluation.objective31_eval_comments %></td>
    <td><%= evaluation.objective31_qualifier %></td>
    <td><%= evaluation.objective31_evalq %></td>
    <td><%= evaluation.nextpobjective31 %></td>
    <td><%= evaluation.category_name_2 %></td>
    <td><%= evaluation.objective12 %></td>
    <td><%= evaluation.objective12_comments %></td>
    <td><%= evaluation.objective12_eval_comments %></td>
    <td><%= evaluation.objective12_qualifier %></td>
    <td><%= evaluation.objective12_evalq %></td>
    <td><%= evaluation.nextpobjective12 %></td>
    <td><%= evaluation.objective22 %></td>
    <td><%= evaluation.objective22_comments %></td>
    <td><%= evaluation.objective22_eval_comments %></td>
    <td><%= evaluation.objective22_qualifier %></td>
    <td><%= evaluation.objective22_evalq %></td>
    <td><%= evaluation.nextpobjective22 %></td>
    <td><%= evaluation.objective32 %></td>
    <td><%= evaluation.objective32_comments %></td>
    <td><%= evaluation.objective32_eval_comments %></td>
    <td><%= evaluation.objective32_qualifier %></td>
    <td><%= evaluation.objective32_evalq %></td>
    <td><%= evaluation.nextpobjective32 %></td>
    <td><%= evaluation.category_name_3 %></td>
    <td><%= evaluation.objective13 %></td>
    <td><%= evaluation.objective13_comments %></td>
    <td><%= evaluation.objective13_eval_comments %></td>
    <td><%= evaluation.objective13_qualifier %></td>
    <td><%= evaluation.objective13_evalq %></td>
    <td><%= evaluation.nextpobjective13 %></td>
    <td><%= evaluation.objective23 %></td>
    <td><%= evaluation.objective23_comments %></td>
    <td><%= evaluation.objective23_eval_comments %></td>
    <td><%= evaluation.objective23_qualifier %></td>
    <td><%= evaluation.objective23_evalq %></td>
    <td><%= evaluation.nextpobjective23 %></td>
    <td><%= evaluation.objective33 %></td>
    <td><%= evaluation.objective33_comments %></td>
    <td><%= evaluation.objective33_eval_comments %></td>
    <td><%= evaluation.objective33_qualifier %></td>
    <td><%= evaluation.objective33_evalq %></td>
    <td><%= evaluation.category_name_4 %></td>
    <td><%= evaluation.objective14 %></td>
    <td><%= evaluation.objective14_comments %></td>
    <td><%= evaluation.objective14_eval_comments %></td>
    <td><%= evaluation.objective14_qualifier %></td>
    <td><%= evaluation.objective14_evalq %></td>
    <td><%= evaluation.nextpobjective14 %></td>
    <td><%= evaluation.objective24 %></td>
    <td><%= evaluation.objective24_comments %></td>
    <td><%= evaluation.objective24_eval_comments %></td>
    <td><%= evaluation.objective24_qualifier %></td>
    <td><%= evaluation.objective24_evalq %></td>
    <td><%= evaluation.nextpobjective24 %></td>
    <td><%= evaluation.objective34 %></td>
    <td><%= evaluation.objective34_comments %></td>
    <td><%= evaluation.objective34_eval_comments %></td>
    <td><%= evaluation.objective34_qualifier %></td>
    <td><%= evaluation.objective34_evalq %></td>
    <td><%= evaluation.nextpobjective34 %></td>
    <td><%= evaluation.nextpobjective34 %></td>
    <td><%= evaluation.category_name_4 %></td>
    <td><%= evaluation.objective14 %></td>
    <td><%= evaluation.objective14_comments %></td>
    <td><%= evaluation.objective14_eval_comments %></td>
    <td><%= evaluation.objective14_qualifier %></td>
    <td><%= evaluation.objective14_evalq %></td>
    <td><%= evaluation.nextpobjective14 %></td>
    <td><%= evaluation.objective24 %></td>
    <td><%= evaluation.objective24_comments %></td>
    <td><%= evaluation.objective24_eval_comments %></td>
    <td><%= evaluation.objective24_qualifier %></td>
    <td><%= evaluation.objective24_evalq %></td>
    <td><%= evaluation.nextpobjective24 %></td>
    <td><%= evaluation.objective34 %></td>
    <td><%= evaluation.objective34_comments %></td>
    <td><%= evaluation.objective34_eval_comments %></td>
    <td><%= evaluation.objective34_qualifier %></td>
    <td><%= evaluation.objective34_evalq %></td>
    <td><%= evaluation.nextpobjective34 %></td>
    <td><%= evaluation.category_name_5 %></td>
    <td><%= evaluation.objective15 %></td>
    <td><%= evaluation.objective15_comments %></td>
    <td><%= evaluation.objective15_eval_comments %></td>
    <td><%= evaluation.objective15_qualifier %></td>
    <td><%= evaluation.objective15_evalq %></td>
    <td><%= evaluation.nextpobjective15 %></td>
    <td><%= evaluation.objective25 %></td>
    <td><%= evaluation.objective25_comments %></td>
    <td><%= evaluation.objective25_eval_comments %></td>
    <td><%= evaluation.objective25_qualifier %></td>
    <td><%= evaluation.objective25_evalq %></td>
    <td><%= evaluation.nextpobjective25 %></td>
    <td><%= evaluation.objective35 %></td>
    <td><%= evaluation.objective35_comments %></td>
    <td><%= evaluation.objective35_eval_comments %></td>
    <td><%= evaluation.objective35_qualifier %></td>
    <td><%= evaluation.objective35_evalq %></td>
    <td><%= evaluation.nextpobjective35 %></td>
    <td><%= evaluation.overalleval %></td>
    <td><%= evaluation.user_id %></td>
    <td><%= evaluation.year %></td>
    <td><%= evaluation.evaluator_id %></td>
    <td><%= link_to 'Show', evaluation %></td>
    <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
    <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Aplicatia de evaluare a performantei", "http://intranet.carpatica.ro" %>
    by <%= link_to "Adrian Chira", "http://adrianchira.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">Eval</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                        <% if user_signed_in? %>
                        	<li><%= link_to "Vezi evaluare", "#" %></li>
                        	<li><%= link_to "Autoevaluare", "#" %></li>
                        	<% @user = current_user %>
                        	 <% if @user.is_admin = true %>
                        			<li><%= link_to "Adauga angajat", new_user_registration_path %></li>
                        			<li><%= link_to "Modifica angajat", "#" %></li>
                        			<li><%= link_to "Sterge Angajat", "#" %></li>
                        	 <% end %>
                        	 <% if @user.is_evaluator = true %>
                        			<li><%= link_to "Adauga o evaluare", "#" %></li>
                        	 <% end %>
                        <% end %>
                    </ul>
                    <ul class="nav pull-right">

                      <% if user_signed_in? %>
                      <% @user = current_user %>
                      	<li class="dropdown">
                      		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      		<%= image_tag(current_user.image(:tiny), :alt => current_user.name, :title => current_user.name) %>
                    <b class="caret"></b>
                    </a>
                      		<ul class="dropdown-menu">
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      		</ul>
                       
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
            </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplicatia de evaluare a performantei</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
    <%= yield %>

    <%= render 'layouts/footer' %>
</div>

  </body>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "Aplicatia de evaluare a performantei", "http://intranet.carpatica.ro" %>
  este aplicatia pentru implementarea evaluarii personalului.
</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
	<% if user_signed_in? %> 
	<h1>Bine ai revenit <% current_user.name %> !</h1>
	<% else %>
	<h1>Bine ai revenit!</h1>
	<% end %>
	<p>
	  You've found the home page for the
	  <%= link_to "Aplicatia de evaluare a performantei", "http://intranet.carpatica.ro" %>
	  application.
	</p>
	<p>
	  <%= link_to "Login", new_user_session_path, class: "btn btn-large btn-primary" %>
	</p>
</div>

app/views/years/_form.html.erb
<%= simple_form_for(@year) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :year %>
    <%= f.input :year_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/years/edit.html.erb
<h1>Editing year</h1>

<%= render 'form' %>

<%= link_to 'Show', @year %> |
<%= link_to 'Back', years_path %>

app/views/years/index.html.erb
<h1>Listing years</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @years.each do |year| %>
  <tr>
    <td><%= year.year %></td>
    <td><%= year.year_id %></td>
    <td><%= link_to 'Show', year %></td>
    <td><%= link_to 'Edit', edit_year_path(year) %></td>
    <td><%= link_to 'Destroy', year, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Year', new_year_path %>

app/views/years/new.html.erb
<h1>New year</h1>

<%= render 'form' %>

<%= link_to 'Back', years_path %>

app/views/years/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @year.year %>
</p>

<p>
  <b>Year:</b>
  <%= @year.year_id %>
</p>


<%= link_to 'Edit', edit_year_path(@year) %> |
<%= link_to 'Back', years_path %>